name: tekartik_midi
version: 0.3.0
description: midi
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  collection: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2

dev_dependencies:
  dev_test: any
  test: any
  path: any
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
